### ISSUE TITLE
error in demoGaussianRBM_Faces

### ISSUE THREAD

**Issue by subhaprakash0106** [dustinstansbury/medal#1]
when i was running the below code .I get this error..

> > demoGaussianRBM_Faces

Here we train an RBM with Continuous inputs (Faces Dataset).
Undefined function 'notDefined' for input arguments of type 'char'.

Error in rbm (line 72)
        if notDefined('arch')

Error in demoGaussianRBM_Faces (line 22)
r = rbm(arch)

**Comment by dustinstansbury** [comment]
make sure to run the command startLearning.m in the root medal directory. it will add the path to the function notDefined.m
